
import java.awt.HeadlessException;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Korisnik
 */
public class GlavnaForma extends javax.swing.JFrame {
    private KonfiguracijaPanela konfiguracija;
    private ApstrakcijaPanela panelIme;
    private ApstrakcijaPanela panelPrezime;
    private ApstrakcijaPanela panelPol;
    private ApstrakcijaPanela panelMesto;
   private javax.swing.JButton btnSacuvajOsobu;

     public GlavnaForma(KonfiguracijaPanela konfiguracija) {
        this.konfiguracija = konfiguracija;
        initComponents();
        getContentPane().setLayout(new java.awt.BorderLayout());
        napraviPanele();
    }

    public JButton getBtnSacuvajOsobu() {
        return btnSacuvajOsobu;
    }

    public void setBtnSacuvajOsobu(JButton btnSacuvajOsobu) {
        this.btnSacuvajOsobu = btnSacuvajOsobu;
    }

    public ApstrakcijaPanela getPanelIme() {
        return panelIme;
    }

    public ApstrakcijaPanela getPanelPrezime() {
        return panelPrezime;
    }

    public ApstrakcijaPanela getPanelPol() {
        return panelPol;
    }

    public ApstrakcijaPanela getPanelMesto() {
        return panelMesto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void napraviPanele() {
        getContentPane().removeAll(); // počistimo sve

        javax.swing.JPanel centralni = new javax.swing.JPanel();
        centralni.setLayout(new java.awt.GridLayout(0, 1));

        // ---------------- Ime ----------------
        if (konfiguracija.getTipIme() == TipUnosa.TEKSTUALNI_UNOS) {
            panelIme = new TekstPanel("Ime");
        } else {
            panelIme = new TekstPanel("Ime");
        }
        centralni.add((javax.swing.JComponent) panelIme);

        // ---------------- Prezime ----------------
        if (konfiguracija.getTipPrezime() == TipUnosa.TEKSTUALNI_UNOS) {
            panelPrezime = new TekstPanel("Prezime");
        } else {
            panelPrezime = new TekstPanel("Prezime");
        }
        centralni.add((javax.swing.JComponent) panelPrezime);

        // ---------------- Pol ----------------
        if (konfiguracija.getTipPol() == TipUnosa.TEKSTUALNI_UNOS) {
            panelPol = new TekstPanel("Pol");
        } else if (konfiguracija.getTipPol() == TipUnosa.PADAJUCA_LISTA) {
            panelPol = new ComboPanel("Pol", new String[]{"Muški", "Ženski"});
        } else if (konfiguracija.getTipPol() == TipUnosa.RADIO_DUGMAD) {
            panelPol = new RadioPanel("Pol",new String[]{"Muški", "Ženski"});
        }
        centralni.add((javax.swing.JComponent) panelPol);

        // ---------------- Mesto ----------------
        if (konfiguracija.getTipMesto() == TipUnosa.TEKSTUALNI_UNOS) {
            panelMesto = new TekstPanel("Mesto");
        } else if (konfiguracija.getTipMesto() == TipUnosa.PADAJUCA_LISTA) {
            panelMesto = new ComboPanel("Mesto", new String[]{"Beograd", "Novi Sad", "Niš"});
        } 
        centralni.add((javax.swing.JComponent) panelMesto);

        // dugme na kraj
        btnSacuvajOsobu = new javax.swing.JButton("Sačuvaj osobu");
        btnSacuvajOsobu.addActionListener(e -> sacuvajOsobu());
        centralni.add(btnSacuvajOsobu);

        getContentPane().add(centralni, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
        revalidate();
        repaint();
    }

    private void sacuvajOsobu() {
    }

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
